theme: jekyll-theme-slate
title :  Bryan Ramirez' Project Portfolio
description : Here you will find a collection of projects and ideas put together to demonstrate a potential path to a career as a developer. 
